name: Update MLB data (FanGraphs)

on:
  schedule:
    # 09:15 UTC daily (5:15am ET) – change as you like
    - cron: "15 9 * * *"
  workflow_dispatch: {}   # allow manual runs

permissions:
  contents: write         # allow pushing CSVs back to the repo

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install R deps (cached)
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::readr
            any::dplyr
            any::stringr
            any::httr

      - name: Run updater
        run: Rscript scripts/update_data.R

      - name: Commit & push refreshed CSVs
        uses: EndBug/add-and-commit@v9
        with:
          add: |
            batters_2025_2025.csv
            pitchers_2025_2025.csv
          author_name: github-actions
          author_email: actions@github.com
          message: "chore(data): refresh FanGraphs 2025 season-to-date"

